name: Run tests on Eva server
'on': workflow_dispatch
jobs:
  connect_and_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy src to Eva
        run: |
          sshpass -p ${{ secrets.EVA_PASSWORD }} scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r . ${{ secrets.EVA_USER }}@${{ secrets.EVA_HOST }}:~/ifj/tmp
      # TODO - run tests
      # TODO - get results somehow
      # TODO - clean up
