name: Run tests on Eva server
'on': workflow_dispatch
jobs:
  connect_and_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Copy src to Eva
        run: |
          sshpass -p ${{ secrets.EVA_PASSWORD }} scp -r src ${{ secrets.EVA_USER }}@${{ secrets.EVA_HOST }}

